version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: quanlymuonsach_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: quanlymuonsach
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - quanlymuonsach_network

  # MongoDB Express - Web-based MongoDB admin interface (optional)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: quanlymuonsach_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - quanlymuonsach_network

volumes:
  mongodb_data:
    driver: local

networks:
  quanlymuonsach_network:
    driver: bridge